#!/usr/bin/env bash
# Copyright (C) 2021-2025 Bytedance Ltd. and/or its affiliates

VERSION="2.1"
chmod 755 /opt/volclava-${VERSION}/lib/liblsf.a || true
chmod 755 /opt/volclava-${VERSION}/lib/liblsbatch.a || true

chmod 755 /etc/profile.d/volclava.sh || true
chmod 755 /etc/profile.d/volclava.csh || true
chmod 755 /opt/volclava-${VERSION}/etc/volclava.sh || true
chmod 755 /opt/volclava-${VERSION}/etc/volclava.csh || true

source /etc/profile.d/volclava.sh || true

chmod 755 /etc/init.d/volclava || true
chmod 755 /opt/volclava-${VERSION}/etc/volclava || true

if [ -n "$volclavaadmin" ]; then
    VOLCADMIN="$volclavaadmin"
else
    VOLCADMIN="volclava"
fi

groupadd -f ${VOLCADMIN} > /dev/null 2>&1 || true
useradd -c "volclava Administrator" -g ${VOLCADMIN} -m -d /home/${VOLCADMIN} ${VOLCADMIN} > /dev/null 2>&1 || true

chown -R ${VOLCADMIN}:${VOLCADMIN} /opt/volclava-${VERSION}/*
chgrp -R ${VOLCADMIN} /opt/volclava-${VERSION}/*
