#!/usr/bin/env bash
# Copyright (C) 2021-2025 Bytedance Ltd. and/or its affiliates

case "$1" in
    remove)
        rm -f /etc/profile.d/volclava* >/dev/null 2>&1  || true
        ;;
    purge)
        rm -f /etc/profile.d/volclava* >/dev/null 2>&1  || true
        ;;
    upgrade)
        ;;
    *)
        exit 1
        ;;
esac

exit 0
